[project]
name = "ayon-ui-lib"
version = "0.1.0"
description = "A Qt Widget library based on AYON's React Component Library"
readme = "README.md"
requires-python = ">=3.9.6"
dependencies = [
    "pyside6>=6.9.2",
    "qt-material-icons>=0.2.0",
    "qtpy>=2.4.3",
    "ruff>=0.12.12",
]
