[project]
name = "ayon-ui-qt"
version = "0.1.0"
description = "A Qt Widget library based on AYON's React Component Library"
readme = "README.md"
requires-python = ">=3.9.6"
dependencies = [
    "pyside6>=6.10.0",
    "qtpy>=2.4.3",
    "ruff>=0.11.4",
]
